### ISSUE TITLE
Comparison with Deno

### ISSUE THREAD

**Issue by talentlessguy** [elsaland/elsa#13]
Hello, the project looks really cool, looking forward to the http API!

However, I'd like to suggest to add a comparison table with Deno, e.g. perf, features, size comparison.

I've seen Deno vs Elsa benchmarks, but a comparison table (either in readme or separate file) with feature lists would be cool as well :D

**Comment by tooolbox** [comment]
Also perhaps a variety of benchmarks rather than just a few console.log statements 😉 

...Well, I see there are more now, but even so.

**Comment by divy-work** [comment]
I agree @talentlessguy @tooolbox. Perhaps, It'd be nice to have a `COMPARISION.md` :smile:

**Comment by divy-work** [comment]
I've added a pretty basic comparison table, although there is more to add. Happy to accept any PRs for the same
