### ISSUE TITLE
elsa/quickjs should fork bellard/quickjs

### ISSUE THREAD

**Issue by rhysd** [elsaland/elsa#48]
elsa/quickjs forks lithdew/quickjs:

https://github.com/elsaland/quickjs

But it's not an official repository and its owner is not an author.

Recently the author of quickjs created their account at GitHub and hosted quickjs repository:

https://github.com/bellard/quickjs

It's official and maintained. I strongly recommend elsa to fork the official repository.

**Comment by littledivy** [comment]
https://github.com/elsaland/quickjs is a fork of **go bindings for quickjs** (lithdew/quickjs) and not quickjs itself

**Comment by rhysd** [comment]
oh, ok. I understood. Thank you for the point.
