### ISSUE TITLE
Ineffectual sync.WaitGroup in ops.Serve

### ISSUE THREAD

**Issue by samhza** [elsaland/elsa#77]
https://github.com/elsaland/elsa/blob/0819922b24f01849de855ff2852f2f28631fc1cb/core/ops/serve.go#L66
This call to `wg.Wait` is unreachable because the `for` loop preceding it never breaks. As a fix, a `chan error` should be used instead of a `sync.WaitGroup` so the error from `http.ListenAndServe` can be returned as well (see #75.)

**Comment by littledivy** [comment]
Fixed in #78. Can we close this @samhza?
