### ISSUE TITLE
Support shebang

### ISSUE THREAD

**Issue by mattn** [elsaland/elsa#98]
Or `elsa install myapp.ts` to make standalone script.

**Comment by littledivy** [comment]
I'm in favour of `elsa install` 👍

**Comment by buttercubz** [comment]
I think we should opt for an option similar to the one used by deno, take the file to install and then generate the minified then generate a `.cmd` (for windows) or `.sh` (for mac or linux) file and point to a minified file

**CC** @littledivy

**Comment by littledivy** [comment]
Agree with @buttercubz - #106 implements a logic for bundling + installing script
